### ISSUE TITLE
Cannot read a space name or space is not defined

### ISSUE THREAD

**Issue by oybekdevuz** [tarantool/node-tarantool-driver#55]
//tarantool service file

```
export class TarantoolService {  
  private connection: TarantoolConnection;  
  
  constructor() {  
    this.connection = new TarantoolConnection({  
      host: 'localhost',  
      port: 3301,  
      username: 'tarantool',  
      password: 'mypassword',
      lazyConnect: true 
    });  

    this.connection.on('error', (err: any) => {
    console.error('[tarantool-driver] Error event:', err);
  });
  }  

  async findAll(spaceName: string, limit: number = 100, offset: number = 0): Promise<any[]> {  
    console.log(spaceName);
    
    return await this.connection.select(  
      spaceName,   
      'primary',   
      limit,   
      offset,   
      'all',   
      []  
    );  
  }  
}
export default TarantoolService;
```

// users.ts file
```
const tarantoolService = new TarantoolService();

app.get("test", async (ctx) => {
  try {
    await tarantoolService.connect(); // Ensure connection is established
        const newRecord: any[] = await tarantoolService.findAll('users');  
    console.log('Created:', newRecord);  
    // ... your database operations  
    return ctx.json({ success: true }); // Add this return  
  } catch (error) {
    console.error('Error:', error);
    return ctx.json({ error: error.message }, 500); // Add error response  
  }
});
```
**it is logging my space name correctly:**

`users` // this is my space name.
```
Error: Error {
  message: "Cannot read a space name or space is not defined",
  name: "TarantoolError",
  originalLine: 74,
  originalColumn: 30,
  stack: "Error\n    at <anonymous> (/home/admin-tadi/Documents/Gitlab/school-tarantol/node_modules/tarantool-driver/lib/utils.js:86:9)\n    at <anonymous> (/home/admin-tadi/Documents/Gitlab/school-tarantol/node_modules/tarantool-driver/lib/commands.js:46:15)\n    at processTicksAndRejections (native:7:39)",
  toString: [Function: toString],
}

```

**Also when I show in console it is aviable:**

```
arantool> box.space.users
---
- is_local: false
  engine: memtx
  before_replace: 'function: 0x71408e5252c8'
  field_count: 0
  is_sync: false
  on_replace: 'function: 0x71408e525290'
  state:
    is_sync: false
  temporary: false
  index:
    0: &0
      unique: true
      parts:
      - fieldno: 1
        sort_order: asc
        type: number
        exclude_null: false
        is_nullable: false
      hint: true
      id: 0
      type: TREE
      space_id: 513
      name: primary
    primary: *0
  type: normal
  enabled: true
  name: users
  id: 513
...
```
